  /* Formatted on 6/21/2023 5:00:32 PM (QP5 v5.365) */
  SELECT HOU.NAME
             OPERATING_UNIT,
         AC.CUSTOMER_NUMBER,
         AC.CUSTOMER_NAME,
         OOH.ORDER_NUMBER,
         TRUNC (OOH.ORDERED_DATE)
             ORDER_DATE,
         OOL.ORDERED_ITEM,
         MSIB.DESCRIPTION,
         OOL.ORDER_QUANTITY_UOM
             UOM,
         SUM (OOL.ORDERED_QUANTITY)
             ORDERED_QUANTITY,
         SUM (OOL.SHIPPED_QUANTITY)
             SHIPPED_QUANTITY,
         SUM (OOL.ORDERED_QUANTITY) - SUM (OOL.SHIPPED_QUANTITY)
             BALANCE_QTY,
         OOL.UNIT_SELLING_PRICE,
         SUM (OOL.ORDERED_QUANTITY) * OOL.UNIT_SELLING_PRICE
             AS TOTAL_AMOUNT
    FROM APPS.OE_ORDER_HEADERS_ALL OOH,
         APPS.OE_ORDER_LINES_ALL   OOL,
         APPS.XX_AR_CUSTOMERS_ALL_V AC,
         APPS.MTL_SYSTEM_ITEMS_B   MSIB,
         APPS.HR_OPERATING_UNITS   HOU
   WHERE     OOH.HEADER_ID = OOL.HEADER_ID
         AND OOH.SOLD_TO_ORG_ID = AC.CUSTOMER_ID
         AND MSIB.INVENTORY_ITEM_ID = OOL.INVENTORY_ITEM_ID
         AND MSIB.ORGANIZATION_ID = OOL.SHIP_FROM_ORG_ID
         AND OOH.ORG_ID = HOU.ORGANIZATION_ID
         AND ( :P_ORG_ID IS NULL OR OOH.ORG_ID = :P_ORG_ID)
         AND ( :P_CUSTOMER_ID IS NULL OR OOH.SOLD_TO_ORG_ID = :P_CUSTOMER_ID)
         AND TRUNC (OOH.ORDERED_DATE) BETWEEN :P_FROM_DATE AND :P_TO_DATE
GROUP BY HOU.NAME,
         AC.CUSTOMER_NUMBER,
         AC.CUSTOMER_NAME,
         OOH.ORDER_NUMBER,
         TRUNC (OOH.ORDERED_DATE),
         OOL.ORDERED_ITEM,
         MSIB.DESCRIPTION,
         OOL.ORDER_QUANTITY_UOM,
         OOL.UNIT_SELLING_PRICE